# Generated by Django 4.0.2 on 2022-06-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
